---
- hosts: all
  vars_files:
    - config
  tasks:
    - name: Ping all hosts
      ping:

    - name: Fetch Timezone
      fetch:
        dest=backup/{{ansible_hostname}}/etc/timezone
        src=/etc/timezone
        flat=yes

    - name: Fetch CumulusLinux Configuration
      synchronize:
        mode=pull
        src=/etc/cumulus
        dest=backup/{{ ansible_hostname }}/etc

    - name: Fetch Network Configuration
      synchronize:
        mode=pull
        src=/etc/network
        dest=backup/{{ ansible_hostname }}/etc

    - name: Fetch User Auth file
      fetch:
        dest=backup/{{ ansible_hostname }}/{{ item }}
        src={{ item }}
        flat=yes
      become: true
      with_items:
        - "/etc/passwd"
        - "/etc/shadow"
