---
- hosts: all
  vars_files:
    - config
  tasks:
    - name: Check All Hosts Alive
      ping:

    - name: Fetch Timezone
      fetch:
        dest={{ BACKUP_ROOT_DIR }}/{{ansible_hostname}}/etc/timezone
        src=/etc/timezone
        flat=yes

    - name: Fetch CumulusLinux Configuration
      synchronize:
        mode=pull
        src=/etc/cumulus
        dest={{ BACKUP_ROOT_DIR }}/{{ ansible_hostname }}/etc

    - name: Fetch Network Configuration
      synchronize:
        mode=pull
        src=/etc/network
        dest={{ BACKUP_ROOT_DIR }}/{{ ansible_hostname }}/etc

    - name: Fetch User Auth file
      fetch:
        dest={{ BACKUP_ROOT_DIR }}/{{ ansible_hostname }}/{{ item }}
        src={{ item }}
        flat=yes
      become: true
      with_items:
        - "/etc/passwd"
        - "/etc/shadow"

    - name: Fetch Quagga Configuration
      synchronize:
        mode=pull
        src=/etc/quagga
        dest={{ BACKUP_ROOT_DIR }}/{{ ansible_hostname }}/etc

    - name: Fetch MOTD file
      fetch:
        dest={{ BACKUP_ROOT_DIR }}/{{ ansible_hostname }}/etc/motd
        src=/etc/motd
        flat=yes

