---
- name: Import Timezone
  copy:
    dest: /etc/timezone
    src: "{{ inventory_dir }}/conf/{{inventory_hostname}}/etc/timezone"
  become: true

- name: Import CumulusLinux Configuration
  copy:
    dest: /etc/
    src: "{{ inventory_dir }}/conf/{{ inventory_hostname }}/etc/cumulus"

- name: Import Network Configuration
  copy:
    dest: /etc/network/interfaces
    src: "{{ inventory_dir }}/conf/{{ inventory_hostname }}/etc/network/interfaces"

- name: Import User Auth file
  copy:
    dest: "{{ item }}"
    src: "{{ inventory_dir }}/conf/{{ inventory_hostname }}/{{ item }}"
  become: true
  with_items:
    - "/etc/passwd"
    - "/etc/shadow"

#XXX
#- name: Import Quagga Configuration
#  copy:
#    dest: /etc/quagga
#    src: "{{ inventory_dir }}/conf/{{ inventory_hostname }}/etc/"
#    mode: pull
#    rsync_path: "sudo -u quagga rsync"

- name: Import MOTD file
  copy:
    dest: /etc/motd
    src: "{{ inventory_dir }}/conf/{{ inventory_hostname }}/etc/motd"
  become: true

